### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by d0ugal** [notpushkin/mkdocs-alabaster#1]
I tried this with the MkDocs documentation, it generally looks great. The Navigation isn't showing on the left however. I think it might not be working, but perhaps I am doing something wrong?

**Comment by notpushkin** [comment]
For now I've left just TOC in the sidebar. That's what http://docs.python-requests.org/ or http://flask.pocoo.org/docs/ use. I just forgot to remove the Navigation header, I'll fix this ASAP.

More navigation options will be added then, probably as a part of configurable sidebar (something like that:)

``` yaml
extra:
  sidebars:
    - about
    - navigation/pocoo # navigation/fabfile, navigation/paramiko
    - searchbox
    - github/star:
        repo: iamale/mkdocs-alabaster
```
